# Generated by Django 2.2.6 on 2019-10-28 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('DA', 'destopApp'), ('WA', 'webApp'), ('AA', 'androidApp')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('B', 'Bug'), ('I', 'Improvement'), ('F', 'Feature'), ('E', 'Epic')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('created_date', models.DateField(verbose_name='date created')),
                ('fixed_date', models.DateField(verbose_name='date fixed')),
                ('activity', models.DateField(verbose_name='last updated date')),
                ('status', models.CharField(choices=[('TD', 'Todo'), ('IP', 'In progress'), ('IR', 'In review'), ('DN', 'Done')], max_length=2)),
                ('priority', models.CharField(choices=[('HH', 'Highest'), ('H', 'High'), ('M', 'Medium'), ('L', 'Lower'), ('LL', 'Lowest')], max_length=2)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issueTracker.Project')),
            ],
        ),
    ]
