# Generated by Django 2.2.6 on 2019-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0002_auto_20191028_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='project_slug', max_length=20),
            preserve_default=False,
        ),
    ]
