# Generated by Django 2.2.6 on 2019-10-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('1', 'Highest'), ('2', 'High'), ('3', 'Medium'), ('4', 'Lower'), ('5', 'Lowest')], max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('1', 'Todo'), ('2', 'In progress'), ('3', 'In review'), ('4', 'Done')], max_length=2),
        ),
    ]
