# Generated by Django 2.2.6 on 2019-11-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0005_auto_20191031_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issues',
            options={'ordering': ['priority', 'status']},
        ),
        migrations.AlterField(
            model_name='issues',
            name='activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last updated date'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date fixed'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('1', 'Highest'), ('2', 'High'), ('3', 'Medium'), ('4', 'Lower'), ('5', 'Lowest'), ('6', 'Done')], default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('1', 'Todo'), ('2', 'In progress'), ('3', 'In review'), ('4', 'Done')], default='1', max_length=2),
        ),
    ]
