# Generated by Django 2.2.6 on 2019-11-02 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0006_auto_20191102_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 22, 33, 24, 799910), verbose_name='date created'),
        ),
    ]
