# Generated by Django 2.2.6 on 2019-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0007_auto_20191102_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_date',
            field=models.DateTimeField(default='03/11/2019 6:18 PM', verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
